version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27018:27017 # Puerto local : Puerto del contenedor
        # por defecto es 27017 pero ya esta en uso
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
